const products=[{name:'SSH Starter',desc:'Untuk browsing ringan dan kebutuhan harian.',price:15000,period:'7 hari',location:'Singapore',host:'sg-01.sshstore.net',ip:'203.0.113.10',port:22,featured:false,features:['1 perangkat aktif','Bandwidth unmetered','Aktivasi instan']},{name:'SSH Premium',desc:'Performa stabil untuk streaming dan kerja.',price:35000,period:'30 hari',location:'Indonesia',host:'id-01.sshstore.net',ip:'203.0.113.20',port:22,featured:true,features:['2 perangkat aktif','Prioritas server','Support 24/7']},{name:'SSH Pro',desc:'Paket panjang untuk penggunaan lebih serius.',price:85000,period:'90 hari',location:'Japan',host:'jp-01.sshstore.net',ip:'203.0.113.30',port:22,featured:false,features:['3 perangkat aktif','Multi-lokasi','Garansi penggantian']}];
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);let balance=Number(localStorage.getItem('sshstore_balance')||0);let lastAccount=null;let savedAccounts=JSON.parse(localStorage.getItem('sshstore_accounts')||'[]');
const grid=document.querySelector('#productGrid');grid.innerHTML=products.map((p,i)=>`<article class="product-card ${p.featured?'featured':''}">${p.featured?'<span class="tag">PALING POPULER</span>':''}<div class="eyebrow">${p.location.toUpperCase()} • ${p.period.toUpperCase()}</div><h3>${p.name}</h3><p class="desc">${p.desc}</p><div class="price">${money(p.price)} <small>/ paket</small></div><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><button class="btn ${p.featured?'btn-primary':'btn-outline'} full buy-btn" data-product="${i}">Beli Sekarang</button></article>`).join('');
function updateBalance(){document.querySelector('#headerBalance').textContent=`Saldo ${money(balance)}`}updateBalance();
const openModal=id=>{const el=document.getElementById(id);el.classList.add('open');el.setAttribute('aria-hidden','false')};const closeModal=el=>{el.closest('.modal').classList.remove('open');el.closest('.modal').setAttribute('aria-hidden','true')};document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b)));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();alert('Prototype: login member siap dihubungkan ke backend.');document.querySelector('#loginModal').classList.remove('open')});document.querySelector('#registerLink').addEventListener('click',e=>{e.preventDefault();alert('Prototype: halaman registrasi member akan ditambahkan pada tahap backend.')});
let selected=25000;document.querySelectorAll('.amount-grid button').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.amount);document.querySelectorAll('.amount-grid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));document.querySelector('#manualTopup').addEventListener('click',()=>{alert(`Prototype: invoice top up ${money(selected)} siap dihubungkan ke payment gateway atau verifikasi manual.`);closeModal(document.querySelector('#manualTopup'))});
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function accountText(account){const lines=['SSH STORE - DETAIL AKUN','========================',`Username : ${account.username}`,`Password : ${account.password}`,`Host     : ${account.host}`];if(account.showIp)lines.push(`IP VPS   : ${account.ip}`);lines.push(`Port SSH: ${account.port}`,`Lokasi   : ${account.location}`,`Masa aktif: ${account.period}`,`Berlaku sampai: ${account.expires}`,`Status   : ${account.status.toUpperCase()}`,'','Simpan file ini dengan aman.');return lines.join('\n')}
function saveAccount(account){savedAccounts=[account,...savedAccounts.filter(x=>x.username!==account.username)];localStorage.setItem('sshstore_accounts',JSON.stringify(savedAccounts));renderSavedAccounts()}
function renderSavedAccounts(){const target=document.querySelector('#savedAccounts');if(!savedAccounts.length){target.innerHTML='<p class="muted-copy">Belum ada akun tersimpan.</p>';return}target.innerHTML=savedAccounts.map((a,i)=>`<button class="saved-account" data-saved-index="${i}"><strong>${escapeHtml(a.username)} • ${escapeHtml(a.location)}</strong><span>${escapeHtml(a.period)} • berlaku sampai ${escapeHtml(a.expires)} • ${escapeHtml(a.status)}</span></button>`).join('');target.querySelectorAll('[data-saved-index]').forEach(b=>b.addEventListener('click',()=>showAccount(savedAccounts[Number(b.dataset.savedIndex)])))}
function showAccount(account){lastAccount=account;account.showIp=Boolean(account.showIp);const rows=[['Username',account.username],['Password',account.password],['Host',account.host],['Port SSH',account.port],['Lokasi',account.location],['Masa aktif',account.period],['Berlaku sampai',account.expires],['Status',account.status.toUpperCase()]];document.querySelector('#accountDetails').innerHTML=rows.map(([k,v])=>`<div class="account-row"><span>${escapeHtml(k)}</span><strong>${escapeHtml(v)}</strong></div>`).join('')+`<div class="ip-option"><button class="btn btn-ghost" id="toggleIp">${account.showIp?'Sembunyikan IP':'Tampilkan IP VPS'}</button><div class="account-row ip-row ${account.showIp?'visible':''}"><span>IP VPS</span><strong>${escapeHtml(account.ip)}</strong></div></div>`;document.querySelector('#toggleIp').addEventListener('click',()=>{account.showIp=!account.showIp;lastAccount=account;document.querySelector('.ip-row').classList.toggle('visible',account.showIp);document.querySelector('#toggleIp').textContent=account.showIp?'Sembunyikan IP':'Tampilkan IP VPS';savedAccounts=savedAccounts.map(x=>x.username===account.username?account:x);localStorage.setItem('sshstore_accounts',JSON.stringify(savedAccounts))});document.querySelector('#accountToast').classList.remove('show');openModal('accountModal')}
function showToast(account){document.querySelector('#toastText').textContent=`${account.username} • klik untuk melihat detail`;document.querySelector('#accountToast').classList.add('show')}
function downloadAccount(){if(!lastAccount)return;const blob=new Blob([accountText(lastAccount)],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ssh-${lastAccount.username}.txt`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#downloadAccount').addEventListener('click',downloadAccount);document.querySelector('#accountToast').addEventListener('click',()=>lastAccount&&showAccount(lastAccount));document.querySelector('#toastClose').addEventListener('click',e=>{e.stopPropagation();document.querySelector('#accountToast').classList.remove('show')});document.querySelector('#myAccounts').addEventListener('click',()=>{renderSavedAccounts();openModal('accountsModal')});renderSavedAccounts();
document.querySelectorAll('.buy-btn').forEach(b=>b.addEventListener('click',()=>{const p=products[Number(b.dataset.product)];if(balance<p.price){alert(`Saldo belum cukup. Tambahkan saldo minimal ${money(p.price-balance)}.`);openModal('topupModal');return}balance-=p.price;localStorage.setItem('sshstore_balance',balance);updateBalance();const suffix=Math.random().toString(36).slice(2,8);const expires=new Date(Date.now()+Number.parseInt(p.period)*86400000).toISOString().slice(0,10);const account={username:`user_${suffix}`,password:`Ssh!${Math.random().toString(36).slice(2,10)}#`,host:p.host,ip:p.ip,port:p.port,location:p.location,period:p.period,expires,status:'active',showIp:false};saveAccount(account);showToast(account)}));

const publicMenuButton=document.querySelector('.menu-btn');const publicNav=document.querySelector('.desktop-nav');publicMenuButton?.addEventListener('click',()=>{publicNav.classList.toggle('mobile-open');publicMenuButton.setAttribute('aria-expanded',publicNav.classList.contains('mobile-open')?'true':'false')});publicNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>publicNav.classList.remove('mobile-open')));
