import http from 'node:http';
import crypto from 'node:crypto';

const PORT=Number(process.env.API_PORT||8788);
const AGENT_URL=process.env.AGENT_URL||'http://127.0.0.1:8787';
const SECRET=process.env.AGENT_SHARED_SECRET;
if(!SECRET){console.error('AGENT_SHARED_SECRET wajib diisi');process.exit(1)}
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
const body=req=>new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>10000)reject(new Error('body too large'))});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{reject(new Error('invalid json'))}});req.on('error',reject)});
function agent(path,method,data={}){const raw=JSON.stringify(data),timestamp=Math.floor(Date.now()/1000).toString(),signature=crypto.createHmac('sha256',SECRET).update(`${timestamp}.${raw}`).digest('hex');return fetch(`${AGENT_URL}${path}`,{method,headers:{'content-type':'application/json','x-agent-timestamp':timestamp,'x-agent-signature':signature},body:method==='GET'?undefined:raw}).then(async r=>{const out=await r.json();if(!r.ok)throw new Error(out.error||'agent error');return out})}
const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,service:'ssh-store-api'});if(req.url==='/v1/accounts'&&req.method==='POST'){const data=await body(req);/* Di produksi: cek session member, product, wallet transaction, dan idempotency key sebelum call agent. */return json(res,201,await agent('/accounts','POST',{username:data.username,days:Number(data.days)}))}if(req.url==='/v1/accounts/extend'&&req.method==='POST'){const data=await body(req);return json(res,200,await agent('/accounts/extend','POST',{username:data.username,days:Number(data.days)}))}if(req.url==='/v1/accounts/status'&&req.method==='POST'){const data=await body(req);return json(res,200,await agent('/accounts/status','POST',{username:data.username,status:data.status}))}if(req.url.startsWith('/v1/accounts/')&&req.method==='DELETE'){const username=decodeURIComponent(req.url.split('/').pop());return json(res,200,await agent(`/accounts/${encodeURIComponent(username)}`,'DELETE',{}))}return json(res,404,{ok:false,error:'not found'})}catch(e){console.error(e);return json(res,400,{ok:false,error:e.message})}});
server.listen(PORT,'127.0.0.1',()=>console.log(`SSH Store API listening on 127.0.0.1:${PORT}`));
